### ISSUE TITLE
Optimizely integration replaying all experiments. Should only replay active experiments?

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-optimizely#1]
_From @jfeldstein on January 21, 2014 19:18_

window.Optimizely.data.experiments contains data on [all experiments in the project](https://www.optimizely.com/docs/api#experiments). 

As is, the integration is copying [all experiments into the user's attributes](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/optimizely.js#L101), which makes it hard/impossible to query for events that were triggered by users who are seeing / have seen a given experiment or variation. 

Would it not be better to only report experiments included in window.Optimizely.data.activeExperiments?

_Copied from original issue: segmentio/analytics.js-integrations#37_

**Comment by ndhoule** [comment]
_From @reinpk on March 14, 2014 18:6_

this seems like a super good idea, the current implementation definitely pollutes other services i find. cc / @ianstormtaylor @DirtyAnalytics thoughts?

**Comment by ndhoule** [comment]
_From @ianstormtaylor on March 14, 2014 18:8_

big +1 haha

**Comment by ndhoule** [comment]
_From @ianstormtaylor on March 14, 2014 18:9_

@DirtyAnalytics was talking about firing events for seeing experiments too. would need to be behind a setting, but could be even more useful for triggering based on a user seeing an experiment (once we switch to active)

**Comment by ndhoule** [comment]
_From @DirtyAnalytics on March 14, 2014 19:23_

+1 to this one, and yea it would be cool to fire an optional event to other services. In particular it's useful for GA since I think it makes more sense than assigning custom dimensions/variables since those are limited and must be defined before hand, whereas an event you can just make a segment of people that did that event :)

**Comment by ndhoule** [comment]
_From @jfeldstein on March 14, 2014 19:31_

Can you segment users by attribute in ga?

The custom code I wrote for this turns all the active
experiments/variations shown into key/value pairs that get identified to
the user (and thus made available as traits on all subsequent events).

This lets you do summary stats taking into account who saw which variations
of which experiment.

~ J

(via phone)

**Comment by hankim813** [comment]
This has been implemented!
