### ISSUE TITLE
Optimizely integration throwing a JS error in IE7

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-optimizely#2]
_From @neodude on March 3, 2015 3:1_

We're getting JS errors, from IE7 only, originating from the analytics.js library. It looks like `Optimizely.prototype.replay` trying to call `window.optimizely.data.state.variationNamesMap`, but `state` in that call chain is undefined. Since [Optimizely no longer supports IE7 as of Oct '14](https://community.optimizely.com/t5/Product-What-s-New/Announcement-Starting-October-15th-2014-we-will-no-longer/ba-p/5164), I'm assuming the Optimizely object state is being partially initialized.

I'm happy to do a PR with a simple null check on `state` (in addition to the null check on `data`), but I wonder if you guys have any better ideas?

(Also, not sure if you guys are supporting IE7 - can't find the browser support info.)

_Copied from original issue: segmentio/analytics.js-integrations#549_

**Comment by hankim813** [comment]
closed due to inactivity, please reopen if still an issue
