### ISSUE TITLE
do not assume value is revenue

### ISSUE THREAD

**Issue by nbrustein** [segment-integrations/analytics.js-integration-optimizely#9]
This link .track() assumes that, if there is a value property, it is an amount of money:

```
var revenue = props.revenue || props.total || props.value;
```

This is an unreasonable assumption.  We have events, for example, in which value is a number of segments.  Our only choice now is to filter all events that have a value and not send them to optimizely.

Seems like this should just be removed, and only "revenue" should be considered revenue.

**Comment by sperand-io** [comment]
@nbrustein sorry about this. Based on a reading of our spec description for the `value` field, I think you're right: https://segment.com/docs/spec/track/#properties

However, I suspect this may be systemic across more of our integrations, so I'm going to scope out what it would look like to audit them all and get this removed.

Thanks for flagging this! We really appreciate it

**Comment by nbrustein** [comment]
Thanks.  Just so you know, I also have an open issue about this in segment support.

**Comment by booleanbetrayal** [comment]
:+1:
